import{a as w,i as c,S as p}from"./assets/vendor-a57f9cde.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const v="https://pixabay.com/api/",P="39809199-e4207359de0c1fdcee2eb8a85";async function g(o,t,s){const a=new URLSearchParams({q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:s,query:o});return(await w.get(`${v}?key=${P}&${a}`)).data}const y=document.querySelector(".search-form"),i=document.querySelector(".load-more"),d=document.querySelector(".gallery");let l="",u=1,m;const f=40;i.classList.add("is-hidden");y.addEventListener("submit",S);i.addEventListener("click",$);async function S(o){if(o.preventDefault(),u=1,l=o.currentTarget.elements.searchQuery.value.trim(),d.innerHTML="",i.classList.add("is-hidden"),l===""){c.warning({message:"The search string cannot be empty. Please specify your search query.",messageColor:"white",backgroundColor:"navy",timeout:3e3,position:"topLeft"});return}try{const t=await g(l,u,f);l===0||t.totalHits===0?c.warning({message:"Sorry, there are no images matching your search query. Please try again.",messageColor:"white",backgroundColor:"navy",timeout:3e3,position:"topLeft"}):(d.insertAdjacentHTML("beforeend",h(t.hits)),m=new p(".gallery a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250}).refresh(),c.info({message:`Hooray! We found ${t.totalHits} images.`,messageColor:"white",backgroundColor:"navy",timeout:3e3,position:"topLeft"}),t.totalHits>f&&i.classList.remove("is-hidden"))}catch(t){handleFetchError(t)}finally{y.reset()}}function h(o){return o.map(({webformatURL:t,id:s,largeImageURL:a,tags:e,likes:r,views:n,comments:b,downloads:L})=>`<a class="gallery__link" href="${a}">
            <div class="gallery-item" id="${s}">
              <img class="gallery-item__img" src="${t}" alt="${e}" loading="lazy" />
              <div class="info">
                <p class="info-item"><b>Likes</b>${r}</p>
                <p class="info-item"><b>Views</b>${n}</p>
                <p class="info-item"><b>Comments</b>${b}</p>
                <p class="info-item"><b>Downloads</b>${L}</p>
              </div>
            </div>
          </a>`).join("")}async function $(){u+=1,m.destroy();try{const o=await g(l,u,f);d.insertAdjacentHTML("beforeend",h(o.hits)),m=new p(".gallery a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250}).refresh();const t=d.querySelectorAll(".gallery__link").length,s=Math.ceil(o.totalHits/40);t<o.totalHits?(i.disabled=!1,C()):(i.classList.add("is-hidden"),c.warning({message:"We are sorry, but you have reached the end of search results.",messageColor:"white",backgroundColor:"navy",timeout:3e3,position:"bottomLeft"}))}catch{}}const C=()=>{const{height:o}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})};
//# sourceMappingURL=commonHelpers.js.map
